nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
        expose_headers: ['Link', 'X-Total-Count']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/auth/':
            allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
            allow_methods: ['POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
            allow_credentials: true
        '^/api/':
            allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
            allow_credentials: true
